version: "3.7"

services:
  postgres:
    image: postgres:11.3-alpine
    container_name: movie_api_postgres
    restart: always
    ports:
      - 15432:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgres/data
  app:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
    container_name: movie_api_app
    ports:
      - 4000:4000
    volumes:
      - .:/workspace
    depends_on:
      - postgres
