version: '3'
services:
  web:
    build:
      context: .

    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=db
      - DATABASE_HOST=toxiproxy
      - DATABASE_PORT=5432
    depends_on:
      - toxiproxy


  toxiproxy:
    image: shopify/toxiproxy:2.1.3
    command: ['-host=0.0.0.0', '-config=/toxiproxy.json']
    volumes:
      - './toxiproxy.json:/toxiproxy.json'
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - './docker/sql:/docker-entrypoint-initdb.d'